#ifndef HINT_H
#define HINT_H

enum Action {MAIN_DECK_TO_DISCARD_DECK, DISCARD_DECK_TO_MAIN_DECK, DISCARD_DECK_TO_DECK, DISCARD_DECK_TO_STACK, DECK_TO_STACK, STACK_TO_DECK, STACK_TO_STACK}

#endif // HINT_H
