/********************************************************************************
** Form generated from reading UI file 'solitaire.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SOLITAIRE_H
#define UI_SOLITAIRE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Solitaire
{
public:
    QWidget *centralWidget;
    QPushButton *stock_deck;
    QPushButton *waste_deck;
    QPushButton *target_deck_2;
    QPushButton *target_deck_3;
    QPushButton *target_deck_4;
    QPushButton *target_deck_1;
    QWidget *working;
    QWidget *working0;
    QPushButton *working0_12;
    QPushButton *working0_1;
    QPushButton *working0_5;
    QPushButton *working0_6;
    QPushButton *working0_8;
    QPushButton *working0_11;
    QPushButton *working0_3;
    QPushButton *working0_9;
    QPushButton *working0_7;
    QPushButton *working0_4;
    QPushButton *working0_10;
    QPushButton *working0_2;
    QPushButton *working0_0;
    QWidget *working1;
    QPushButton *working1_0;
    QPushButton *working1_1;
    QPushButton *working1_2;
    QPushButton *working1_3;
    QPushButton *working1_4;
    QPushButton *working1_5;
    QPushButton *working1_6;
    QPushButton *working1_7;
    QPushButton *working1_8;
    QPushButton *working1_9;
    QPushButton *working1_10;
    QPushButton *working1_11;
    QPushButton *working1_12;
    QPushButton *working1_13;
    QWidget *working2;
    QPushButton *working2_0;
    QPushButton *working2_1;
    QPushButton *working2_2;
    QPushButton *working2_3;
    QPushButton *working2_4;
    QPushButton *working2_5;
    QPushButton *working2_6;
    QPushButton *working2_7;
    QPushButton *working2_8;
    QPushButton *working2_9;
    QPushButton *working2_10;
    QPushButton *working2_11;
    QPushButton *working2_12;
    QPushButton *working2_13;
    QPushButton *working2_14;
    QWidget *working3;
    QPushButton *working3_0;
    QPushButton *working3_1;
    QPushButton *working3_2;
    QPushButton *working3_3;
    QPushButton *working3_4;
    QPushButton *working3_5;
    QPushButton *working3_6;
    QPushButton *working3_7;
    QPushButton *working3_8;
    QPushButton *working3_9;
    QPushButton *working3_10;
    QPushButton *working3_11;
    QPushButton *working3_12;
    QPushButton *working3_13;
    QPushButton *working3_14;
    QPushButton *working3_15;
    QWidget *working4;
    QPushButton *working4_0;
    QPushButton *working4_1;
    QPushButton *working4_2;
    QPushButton *working4_3;
    QPushButton *working4_4;
    QPushButton *working4_5;
    QPushButton *working4_6;
    QPushButton *working4_7;
    QPushButton *working4_8;
    QPushButton *working4_9;
    QPushButton *working4_10;
    QPushButton *working4_11;
    QPushButton *working4_12;
    QPushButton *working4_13;
    QPushButton *working4_14;
    QPushButton *working4_15;
    QPushButton *working4_16;
    QWidget *working5;
    QPushButton *working5_0;
    QPushButton *working5_1;
    QPushButton *working5_2;
    QPushButton *working5_3;
    QPushButton *working5_4;
    QPushButton *working5_5;
    QPushButton *working5_6;
    QPushButton *working5_7;
    QPushButton *working5_8;
    QPushButton *working5_9;
    QPushButton *working5_10;
    QPushButton *working5_11;
    QPushButton *working5_12;
    QPushButton *working5_13;
    QPushButton *working5_14;
    QPushButton *working5_15;
    QPushButton *working5_16;
    QPushButton *working5_17;
    QWidget *working6;
    QPushButton *working6_0;
    QPushButton *working6_1;
    QPushButton *working6_2;
    QPushButton *working6_3;
    QPushButton *working6_4;
    QPushButton *working6_5;
    QPushButton *working6_6;
    QPushButton *working6_7;
    QPushButton *working6_8;
    QPushButton *working6_9;
    QPushButton *working6_10;
    QPushButton *working6_11;
    QPushButton *working6_12;
    QPushButton *working6_13;
    QPushButton *working6_14;
    QPushButton *working6_15;
    QPushButton *working6_16;
    QPushButton *working6_17;
    QPushButton *working6_18;
    QWidget *menu;
    QPushButton *save;
    QPushButton *load;
    QPushButton *undo;
    QPushButton *hint;
    QWidget *info;
    QLabel *moves;
    QLabel *score;
    QLabel *time;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *Solitaire)
    {
        if (Solitaire->objectName().isEmpty())
            Solitaire->setObjectName(QStringLiteral("Solitaire"));
        Solitaire->resize(644, 605);
        Solitaire->setStyleSheet(QStringLiteral("background-color: rgb(78, 154, 6);"));
        centralWidget = new QWidget(Solitaire);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stock_deck = new QPushButton(centralWidget);
        stock_deck->setObjectName(QStringLiteral("stock_deck"));
        stock_deck->setGeometry(QRect(10, 50, 75, 110));
        stock_deck->setCursor(QCursor(Qt::PointingHandCursor));
        stock_deck->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        stock_deck->setFlat(false);
        waste_deck = new QPushButton(centralWidget);
        waste_deck->setObjectName(QStringLiteral("waste_deck"));
        waste_deck->setGeometry(QRect(100, 50, 75, 110));
        waste_deck->setCursor(QCursor(Qt::PointingHandCursor));
        waste_deck->setMouseTracking(false);
        waste_deck->setFocusPolicy(Qt::StrongFocus);
        waste_deck->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        waste_deck->setCheckable(false);
        waste_deck->setAutoDefault(false);
        waste_deck->setFlat(false);
        target_deck_2 = new QPushButton(centralWidget);
        target_deck_2->setObjectName(QStringLiteral("target_deck_2"));
        target_deck_2->setGeometry(QRect(370, 50, 75, 110));
        target_deck_2->setCursor(QCursor(Qt::PointingHandCursor));
        target_deck_2->setMouseTracking(false);
        target_deck_2->setFocusPolicy(Qt::StrongFocus);
        target_deck_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        target_deck_2->setCheckable(false);
        target_deck_2->setAutoDefault(false);
        target_deck_2->setFlat(false);
        target_deck_3 = new QPushButton(centralWidget);
        target_deck_3->setObjectName(QStringLiteral("target_deck_3"));
        target_deck_3->setGeometry(QRect(460, 50, 75, 110));
        target_deck_3->setCursor(QCursor(Qt::PointingHandCursor));
        target_deck_3->setMouseTracking(false);
        target_deck_3->setFocusPolicy(Qt::StrongFocus);
        target_deck_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        target_deck_3->setCheckable(false);
        target_deck_3->setAutoDefault(false);
        target_deck_3->setFlat(false);
        target_deck_4 = new QPushButton(centralWidget);
        target_deck_4->setObjectName(QStringLiteral("target_deck_4"));
        target_deck_4->setGeometry(QRect(550, 50, 75, 110));
        target_deck_4->setCursor(QCursor(Qt::PointingHandCursor));
        target_deck_4->setMouseTracking(false);
        target_deck_4->setFocusPolicy(Qt::StrongFocus);
        target_deck_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        target_deck_4->setCheckable(false);
        target_deck_4->setAutoDefault(false);
        target_deck_4->setFlat(false);
        target_deck_1 = new QPushButton(centralWidget);
        target_deck_1->setObjectName(QStringLiteral("target_deck_1"));
        target_deck_1->setGeometry(QRect(280, 50, 75, 110));
        target_deck_1->setCursor(QCursor(Qt::PointingHandCursor));
        target_deck_1->setMouseTracking(false);
        target_deck_1->setFocusPolicy(Qt::StrongFocus);
        target_deck_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        target_deck_1->setCheckable(false);
        target_deck_1->setAutoDefault(false);
        target_deck_1->setFlat(false);
        working = new QWidget(centralWidget);
        working->setObjectName(QStringLiteral("working"));
        working->setGeometry(QRect(10, 175, 620, 381));
        working->setStyleSheet(QStringLiteral(""));
        working0 = new QWidget(working);
        working0->setObjectName(QStringLiteral("working0"));
        working0->setGeometry(QRect(0, 0, 81, 291));
        working0->setStyleSheet(QLatin1String(" CardStack *stack = game->get_working_stack_by_id(0);\n"
"    if (stack != NULL){\n"
"        int count = stack->get_size();\n"
"        for (int i = 0; i < count; i++) {\n"
"            card = stack->get(i);\n"
"            QPushButton *button = ui->working0->findChildren<QPushButton*>().at(i);\n"
"            if (card->is_turned_face_up()) {\n"
"                QPixmap pixmap(\"../images/\" + QString::fromStdString(card->to_string()) + \".svg\");\n"
"                QIcon ButtonIcon(pixmap);\n"
"                if (button != NULL) {\n"
"                    button->setIcon(ButtonIcon);\n"
"                    button->setIconSize(button->size());\n"
"                }\n"
"            } else {\n"
"                QPixmap pixmap(\"../images/back.svg\");\n"
"                QIcon ButtonIcon(pixmap);\n"
"                if (button != NULL) {\n"
"                    button->setIcon(ButtonIcon);\n"
"                    button->setIconSize(button->size());\n"
"                }\n"
"            }\n"
"        }\n"
"   "
                        "     for (int i = count; i < 13; i++) {\n"
"            QPushButton *button = ui->working0->findChildren<QPushButton*>().at(i);\n"
"            button->setVisible(false);\n"
"        }\n"
"    }"));
        working0_12 = new QPushButton(working0);
        working0_12->setObjectName(QStringLiteral("working0_12"));
        working0_12->setGeometry(QRect(0, 180, 75, 110));
        working0_12->setCursor(QCursor(Qt::PointingHandCursor));
        working0_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_12->setFlat(false);
        working0_1 = new QPushButton(working0);
        working0_1->setObjectName(QStringLiteral("working0_1"));
        working0_1->setGeometry(QRect(0, 15, 75, 110));
        working0_1->setCursor(QCursor(Qt::PointingHandCursor));
        working0_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_1->setFlat(false);
        working0_5 = new QPushButton(working0);
        working0_5->setObjectName(QStringLiteral("working0_5"));
        working0_5->setGeometry(QRect(0, 75, 75, 110));
        working0_5->setCursor(QCursor(Qt::PointingHandCursor));
        working0_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_5->setFlat(false);
        working0_6 = new QPushButton(working0);
        working0_6->setObjectName(QStringLiteral("working0_6"));
        working0_6->setGeometry(QRect(0, 90, 75, 110));
        working0_6->setCursor(QCursor(Qt::PointingHandCursor));
        working0_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_6->setFlat(false);
        working0_8 = new QPushButton(working0);
        working0_8->setObjectName(QStringLiteral("working0_8"));
        working0_8->setGeometry(QRect(0, 120, 75, 110));
        working0_8->setCursor(QCursor(Qt::PointingHandCursor));
        working0_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_8->setFlat(false);
        working0_11 = new QPushButton(working0);
        working0_11->setObjectName(QStringLiteral("working0_11"));
        working0_11->setGeometry(QRect(0, 165, 75, 110));
        working0_11->setCursor(QCursor(Qt::PointingHandCursor));
        working0_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_11->setFlat(false);
        working0_3 = new QPushButton(working0);
        working0_3->setObjectName(QStringLiteral("working0_3"));
        working0_3->setGeometry(QRect(0, 45, 75, 110));
        working0_3->setCursor(QCursor(Qt::PointingHandCursor));
        working0_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_3->setFlat(false);
        working0_9 = new QPushButton(working0);
        working0_9->setObjectName(QStringLiteral("working0_9"));
        working0_9->setGeometry(QRect(0, 135, 75, 110));
        working0_9->setCursor(QCursor(Qt::PointingHandCursor));
        working0_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_9->setFlat(false);
        working0_7 = new QPushButton(working0);
        working0_7->setObjectName(QStringLiteral("working0_7"));
        working0_7->setGeometry(QRect(0, 105, 75, 110));
        working0_7->setCursor(QCursor(Qt::PointingHandCursor));
        working0_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_7->setFlat(false);
        working0_4 = new QPushButton(working0);
        working0_4->setObjectName(QStringLiteral("working0_4"));
        working0_4->setGeometry(QRect(0, 60, 75, 110));
        working0_4->setCursor(QCursor(Qt::PointingHandCursor));
        working0_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_4->setFlat(false);
        working0_10 = new QPushButton(working0);
        working0_10->setObjectName(QStringLiteral("working0_10"));
        working0_10->setGeometry(QRect(0, 150, 75, 110));
        working0_10->setCursor(QCursor(Qt::PointingHandCursor));
        working0_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_10->setFlat(false);
        working0_2 = new QPushButton(working0);
        working0_2->setObjectName(QStringLiteral("working0_2"));
        working0_2->setGeometry(QRect(0, 30, 75, 110));
        working0_2->setCursor(QCursor(Qt::PointingHandCursor));
        working0_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_2->setFlat(false);
        working0_0 = new QPushButton(working0);
        working0_0->setObjectName(QStringLiteral("working0_0"));
        working0_0->setGeometry(QRect(0, 0, 75, 110));
        working0_0->setCursor(QCursor(Qt::PointingHandCursor));
        working0_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working0_0->setFlat(false);
        working0_0->raise();
        working0_1->raise();
        working0_2->raise();
        working0_3->raise();
        working0_4->raise();
        working0_5->raise();
        working0_6->raise();
        working0_7->raise();
        working0_8->raise();
        working0_9->raise();
        working0_10->raise();
        working0_11->raise();
        working0_12->raise();
        working1 = new QWidget(working);
        working1->setObjectName(QStringLiteral("working1"));
        working1->setGeometry(QRect(90, 0, 81, 311));
        working1->setStyleSheet(QStringLiteral(""));
        working1_0 = new QPushButton(working1);
        working1_0->setObjectName(QStringLiteral("working1_0"));
        working1_0->setGeometry(QRect(0, 0, 75, 110));
        working1_0->setCursor(QCursor(Qt::PointingHandCursor));
        working1_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_0->setFlat(false);
        working1_1 = new QPushButton(working1);
        working1_1->setObjectName(QStringLiteral("working1_1"));
        working1_1->setGeometry(QRect(0, 15, 75, 110));
        working1_1->setCursor(QCursor(Qt::PointingHandCursor));
        working1_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_1->setFlat(false);
        working1_2 = new QPushButton(working1);
        working1_2->setObjectName(QStringLiteral("working1_2"));
        working1_2->setGeometry(QRect(0, 30, 75, 110));
        working1_2->setCursor(QCursor(Qt::PointingHandCursor));
        working1_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_2->setFlat(false);
        working1_3 = new QPushButton(working1);
        working1_3->setObjectName(QStringLiteral("working1_3"));
        working1_3->setGeometry(QRect(0, 45, 75, 110));
        working1_3->setCursor(QCursor(Qt::PointingHandCursor));
        working1_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_3->setFlat(false);
        working1_4 = new QPushButton(working1);
        working1_4->setObjectName(QStringLiteral("working1_4"));
        working1_4->setGeometry(QRect(0, 60, 75, 110));
        working1_4->setCursor(QCursor(Qt::PointingHandCursor));
        working1_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_4->setFlat(false);
        working1_5 = new QPushButton(working1);
        working1_5->setObjectName(QStringLiteral("working1_5"));
        working1_5->setGeometry(QRect(0, 75, 75, 110));
        working1_5->setCursor(QCursor(Qt::PointingHandCursor));
        working1_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_5->setFlat(false);
        working1_6 = new QPushButton(working1);
        working1_6->setObjectName(QStringLiteral("working1_6"));
        working1_6->setGeometry(QRect(0, 90, 75, 110));
        working1_6->setCursor(QCursor(Qt::PointingHandCursor));
        working1_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_6->setFlat(false);
        working1_7 = new QPushButton(working1);
        working1_7->setObjectName(QStringLiteral("working1_7"));
        working1_7->setGeometry(QRect(0, 105, 75, 110));
        working1_7->setCursor(QCursor(Qt::PointingHandCursor));
        working1_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_7->setFlat(false);
        working1_8 = new QPushButton(working1);
        working1_8->setObjectName(QStringLiteral("working1_8"));
        working1_8->setGeometry(QRect(0, 120, 75, 110));
        working1_8->setCursor(QCursor(Qt::PointingHandCursor));
        working1_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_8->setFlat(false);
        working1_9 = new QPushButton(working1);
        working1_9->setObjectName(QStringLiteral("working1_9"));
        working1_9->setGeometry(QRect(0, 135, 75, 110));
        working1_9->setCursor(QCursor(Qt::PointingHandCursor));
        working1_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_9->setFlat(false);
        working1_10 = new QPushButton(working1);
        working1_10->setObjectName(QStringLiteral("working1_10"));
        working1_10->setGeometry(QRect(0, 150, 75, 110));
        working1_10->setCursor(QCursor(Qt::PointingHandCursor));
        working1_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_10->setFlat(false);
        working1_11 = new QPushButton(working1);
        working1_11->setObjectName(QStringLiteral("working1_11"));
        working1_11->setGeometry(QRect(0, 165, 75, 110));
        working1_11->setCursor(QCursor(Qt::PointingHandCursor));
        working1_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_11->setFlat(false);
        working1_12 = new QPushButton(working1);
        working1_12->setObjectName(QStringLiteral("working1_12"));
        working1_12->setGeometry(QRect(0, 180, 75, 110));
        working1_12->setCursor(QCursor(Qt::PointingHandCursor));
        working1_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_12->setFlat(false);
        working1_13 = new QPushButton(working1);
        working1_13->setObjectName(QStringLiteral("working1_13"));
        working1_13->setGeometry(QRect(0, 195, 75, 110));
        working1_13->setCursor(QCursor(Qt::PointingHandCursor));
        working1_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working1_13->setFlat(false);
        working2 = new QWidget(working);
        working2->setObjectName(QStringLiteral("working2"));
        working2->setGeometry(QRect(180, 0, 75, 321));
        working2->setStyleSheet(QStringLiteral(""));
        working2_0 = new QPushButton(working2);
        working2_0->setObjectName(QStringLiteral("working2_0"));
        working2_0->setGeometry(QRect(0, 0, 75, 110));
        working2_0->setCursor(QCursor(Qt::PointingHandCursor));
        working2_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_0->setFlat(false);
        working2_1 = new QPushButton(working2);
        working2_1->setObjectName(QStringLiteral("working2_1"));
        working2_1->setGeometry(QRect(0, 15, 75, 110));
        working2_1->setCursor(QCursor(Qt::PointingHandCursor));
        working2_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_1->setFlat(false);
        working2_2 = new QPushButton(working2);
        working2_2->setObjectName(QStringLiteral("working2_2"));
        working2_2->setGeometry(QRect(0, 30, 75, 110));
        working2_2->setCursor(QCursor(Qt::PointingHandCursor));
        working2_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_2->setFlat(false);
        working2_3 = new QPushButton(working2);
        working2_3->setObjectName(QStringLiteral("working2_3"));
        working2_3->setGeometry(QRect(0, 45, 75, 110));
        working2_3->setCursor(QCursor(Qt::PointingHandCursor));
        working2_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_3->setFlat(false);
        working2_4 = new QPushButton(working2);
        working2_4->setObjectName(QStringLiteral("working2_4"));
        working2_4->setGeometry(QRect(0, 60, 75, 110));
        working2_4->setCursor(QCursor(Qt::PointingHandCursor));
        working2_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_4->setFlat(false);
        working2_5 = new QPushButton(working2);
        working2_5->setObjectName(QStringLiteral("working2_5"));
        working2_5->setGeometry(QRect(0, 75, 75, 110));
        working2_5->setCursor(QCursor(Qt::PointingHandCursor));
        working2_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_5->setFlat(false);
        working2_6 = new QPushButton(working2);
        working2_6->setObjectName(QStringLiteral("working2_6"));
        working2_6->setGeometry(QRect(0, 90, 75, 110));
        working2_6->setCursor(QCursor(Qt::PointingHandCursor));
        working2_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_6->setFlat(false);
        working2_7 = new QPushButton(working2);
        working2_7->setObjectName(QStringLiteral("working2_7"));
        working2_7->setGeometry(QRect(0, 105, 75, 110));
        working2_7->setCursor(QCursor(Qt::PointingHandCursor));
        working2_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_7->setFlat(false);
        working2_8 = new QPushButton(working2);
        working2_8->setObjectName(QStringLiteral("working2_8"));
        working2_8->setGeometry(QRect(0, 120, 75, 110));
        working2_8->setCursor(QCursor(Qt::PointingHandCursor));
        working2_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_8->setFlat(false);
        working2_9 = new QPushButton(working2);
        working2_9->setObjectName(QStringLiteral("working2_9"));
        working2_9->setGeometry(QRect(0, 135, 75, 110));
        working2_9->setCursor(QCursor(Qt::PointingHandCursor));
        working2_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_9->setFlat(false);
        working2_10 = new QPushButton(working2);
        working2_10->setObjectName(QStringLiteral("working2_10"));
        working2_10->setGeometry(QRect(0, 150, 75, 110));
        working2_10->setCursor(QCursor(Qt::PointingHandCursor));
        working2_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_10->setFlat(false);
        working2_11 = new QPushButton(working2);
        working2_11->setObjectName(QStringLiteral("working2_11"));
        working2_11->setGeometry(QRect(0, 165, 75, 110));
        working2_11->setCursor(QCursor(Qt::PointingHandCursor));
        working2_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_11->setFlat(false);
        working2_12 = new QPushButton(working2);
        working2_12->setObjectName(QStringLiteral("working2_12"));
        working2_12->setGeometry(QRect(0, 180, 75, 110));
        working2_12->setCursor(QCursor(Qt::PointingHandCursor));
        working2_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_12->setFlat(false);
        working2_13 = new QPushButton(working2);
        working2_13->setObjectName(QStringLiteral("working2_13"));
        working2_13->setGeometry(QRect(0, 195, 75, 110));
        working2_13->setCursor(QCursor(Qt::PointingHandCursor));
        working2_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_13->setFlat(false);
        working2_14 = new QPushButton(working2);
        working2_14->setObjectName(QStringLiteral("working2_14"));
        working2_14->setGeometry(QRect(0, 210, 75, 110));
        working2_14->setCursor(QCursor(Qt::PointingHandCursor));
        working2_14->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working2_14->setFlat(false);
        working3 = new QWidget(working);
        working3->setObjectName(QStringLiteral("working3"));
        working3->setGeometry(QRect(270, 0, 75, 335));
        working3->setStyleSheet(QStringLiteral(""));
        working3_0 = new QPushButton(working3);
        working3_0->setObjectName(QStringLiteral("working3_0"));
        working3_0->setGeometry(QRect(0, 0, 75, 110));
        working3_0->setCursor(QCursor(Qt::PointingHandCursor));
        working3_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_0->setFlat(false);
        working3_1 = new QPushButton(working3);
        working3_1->setObjectName(QStringLiteral("working3_1"));
        working3_1->setGeometry(QRect(0, 15, 75, 110));
        working3_1->setCursor(QCursor(Qt::PointingHandCursor));
        working3_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_1->setFlat(false);
        working3_2 = new QPushButton(working3);
        working3_2->setObjectName(QStringLiteral("working3_2"));
        working3_2->setGeometry(QRect(0, 30, 75, 110));
        working3_2->setCursor(QCursor(Qt::PointingHandCursor));
        working3_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_2->setFlat(false);
        working3_3 = new QPushButton(working3);
        working3_3->setObjectName(QStringLiteral("working3_3"));
        working3_3->setGeometry(QRect(0, 45, 75, 110));
        working3_3->setCursor(QCursor(Qt::PointingHandCursor));
        working3_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_3->setFlat(false);
        working3_4 = new QPushButton(working3);
        working3_4->setObjectName(QStringLiteral("working3_4"));
        working3_4->setGeometry(QRect(0, 60, 75, 110));
        working3_4->setCursor(QCursor(Qt::PointingHandCursor));
        working3_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_4->setFlat(false);
        working3_5 = new QPushButton(working3);
        working3_5->setObjectName(QStringLiteral("working3_5"));
        working3_5->setGeometry(QRect(0, 75, 75, 110));
        working3_5->setCursor(QCursor(Qt::PointingHandCursor));
        working3_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_5->setFlat(false);
        working3_6 = new QPushButton(working3);
        working3_6->setObjectName(QStringLiteral("working3_6"));
        working3_6->setGeometry(QRect(0, 90, 75, 110));
        working3_6->setCursor(QCursor(Qt::PointingHandCursor));
        working3_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_6->setFlat(false);
        working3_7 = new QPushButton(working3);
        working3_7->setObjectName(QStringLiteral("working3_7"));
        working3_7->setGeometry(QRect(0, 105, 75, 110));
        working3_7->setCursor(QCursor(Qt::PointingHandCursor));
        working3_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_7->setFlat(false);
        working3_8 = new QPushButton(working3);
        working3_8->setObjectName(QStringLiteral("working3_8"));
        working3_8->setGeometry(QRect(0, 120, 75, 110));
        working3_8->setCursor(QCursor(Qt::PointingHandCursor));
        working3_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_8->setFlat(false);
        working3_9 = new QPushButton(working3);
        working3_9->setObjectName(QStringLiteral("working3_9"));
        working3_9->setGeometry(QRect(0, 135, 75, 110));
        working3_9->setCursor(QCursor(Qt::PointingHandCursor));
        working3_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_9->setFlat(false);
        working3_10 = new QPushButton(working3);
        working3_10->setObjectName(QStringLiteral("working3_10"));
        working3_10->setGeometry(QRect(0, 150, 75, 110));
        working3_10->setCursor(QCursor(Qt::PointingHandCursor));
        working3_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_10->setFlat(false);
        working3_11 = new QPushButton(working3);
        working3_11->setObjectName(QStringLiteral("working3_11"));
        working3_11->setGeometry(QRect(0, 165, 75, 110));
        working3_11->setCursor(QCursor(Qt::PointingHandCursor));
        working3_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_11->setFlat(false);
        working3_12 = new QPushButton(working3);
        working3_12->setObjectName(QStringLiteral("working3_12"));
        working3_12->setGeometry(QRect(0, 180, 75, 110));
        working3_12->setCursor(QCursor(Qt::PointingHandCursor));
        working3_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_12->setFlat(false);
        working3_13 = new QPushButton(working3);
        working3_13->setObjectName(QStringLiteral("working3_13"));
        working3_13->setGeometry(QRect(0, 195, 75, 110));
        working3_13->setCursor(QCursor(Qt::PointingHandCursor));
        working3_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_13->setFlat(false);
        working3_14 = new QPushButton(working3);
        working3_14->setObjectName(QStringLiteral("working3_14"));
        working3_14->setGeometry(QRect(0, 210, 75, 110));
        working3_14->setCursor(QCursor(Qt::PointingHandCursor));
        working3_14->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_14->setFlat(false);
        working3_15 = new QPushButton(working3);
        working3_15->setObjectName(QStringLiteral("working3_15"));
        working3_15->setGeometry(QRect(0, 225, 75, 110));
        working3_15->setCursor(QCursor(Qt::PointingHandCursor));
        working3_15->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working3_15->setFlat(false);
        working4 = new QWidget(working);
        working4->setObjectName(QStringLiteral("working4"));
        working4->setGeometry(QRect(360, 0, 75, 361));
        working4_0 = new QPushButton(working4);
        working4_0->setObjectName(QStringLiteral("working4_0"));
        working4_0->setGeometry(QRect(0, 0, 75, 110));
        working4_0->setCursor(QCursor(Qt::PointingHandCursor));
        working4_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_0->setFlat(false);
        working4_1 = new QPushButton(working4);
        working4_1->setObjectName(QStringLiteral("working4_1"));
        working4_1->setGeometry(QRect(0, 15, 75, 110));
        working4_1->setCursor(QCursor(Qt::PointingHandCursor));
        working4_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_1->setFlat(false);
        working4_2 = new QPushButton(working4);
        working4_2->setObjectName(QStringLiteral("working4_2"));
        working4_2->setGeometry(QRect(0, 30, 75, 110));
        working4_2->setCursor(QCursor(Qt::PointingHandCursor));
        working4_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_2->setFlat(false);
        working4_3 = new QPushButton(working4);
        working4_3->setObjectName(QStringLiteral("working4_3"));
        working4_3->setGeometry(QRect(0, 45, 75, 110));
        working4_3->setCursor(QCursor(Qt::PointingHandCursor));
        working4_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_3->setFlat(false);
        working4_4 = new QPushButton(working4);
        working4_4->setObjectName(QStringLiteral("working4_4"));
        working4_4->setGeometry(QRect(0, 60, 75, 110));
        working4_4->setCursor(QCursor(Qt::PointingHandCursor));
        working4_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_4->setFlat(false);
        working4_5 = new QPushButton(working4);
        working4_5->setObjectName(QStringLiteral("working4_5"));
        working4_5->setGeometry(QRect(0, 75, 75, 110));
        working4_5->setCursor(QCursor(Qt::PointingHandCursor));
        working4_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_5->setFlat(false);
        working4_6 = new QPushButton(working4);
        working4_6->setObjectName(QStringLiteral("working4_6"));
        working4_6->setGeometry(QRect(0, 90, 75, 110));
        working4_6->setCursor(QCursor(Qt::PointingHandCursor));
        working4_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_6->setFlat(false);
        working4_7 = new QPushButton(working4);
        working4_7->setObjectName(QStringLiteral("working4_7"));
        working4_7->setGeometry(QRect(0, 105, 75, 110));
        working4_7->setCursor(QCursor(Qt::PointingHandCursor));
        working4_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_7->setFlat(false);
        working4_8 = new QPushButton(working4);
        working4_8->setObjectName(QStringLiteral("working4_8"));
        working4_8->setGeometry(QRect(0, 120, 75, 110));
        working4_8->setCursor(QCursor(Qt::PointingHandCursor));
        working4_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_8->setFlat(false);
        working4_9 = new QPushButton(working4);
        working4_9->setObjectName(QStringLiteral("working4_9"));
        working4_9->setGeometry(QRect(0, 135, 75, 110));
        working4_9->setCursor(QCursor(Qt::PointingHandCursor));
        working4_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_9->setFlat(false);
        working4_10 = new QPushButton(working4);
        working4_10->setObjectName(QStringLiteral("working4_10"));
        working4_10->setGeometry(QRect(0, 150, 75, 110));
        working4_10->setCursor(QCursor(Qt::PointingHandCursor));
        working4_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_10->setFlat(false);
        working4_11 = new QPushButton(working4);
        working4_11->setObjectName(QStringLiteral("working4_11"));
        working4_11->setGeometry(QRect(0, 165, 75, 110));
        working4_11->setCursor(QCursor(Qt::PointingHandCursor));
        working4_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_11->setFlat(false);
        working4_12 = new QPushButton(working4);
        working4_12->setObjectName(QStringLiteral("working4_12"));
        working4_12->setGeometry(QRect(0, 180, 75, 110));
        working4_12->setCursor(QCursor(Qt::PointingHandCursor));
        working4_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_12->setFlat(false);
        working4_13 = new QPushButton(working4);
        working4_13->setObjectName(QStringLiteral("working4_13"));
        working4_13->setGeometry(QRect(0, 195, 75, 110));
        working4_13->setCursor(QCursor(Qt::PointingHandCursor));
        working4_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_13->setFlat(false);
        working4_14 = new QPushButton(working4);
        working4_14->setObjectName(QStringLiteral("working4_14"));
        working4_14->setGeometry(QRect(0, 210, 75, 110));
        working4_14->setCursor(QCursor(Qt::PointingHandCursor));
        working4_14->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_14->setFlat(false);
        working4_15 = new QPushButton(working4);
        working4_15->setObjectName(QStringLiteral("working4_15"));
        working4_15->setGeometry(QRect(0, 225, 75, 110));
        working4_15->setCursor(QCursor(Qt::PointingHandCursor));
        working4_15->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_15->setFlat(false);
        working4_16 = new QPushButton(working4);
        working4_16->setObjectName(QStringLiteral("working4_16"));
        working4_16->setGeometry(QRect(0, 240, 75, 110));
        working4_16->setCursor(QCursor(Qt::PointingHandCursor));
        working4_16->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working4_16->setFlat(false);
        working5 = new QWidget(working);
        working5->setObjectName(QStringLiteral("working5"));
        working5->setGeometry(QRect(450, 0, 75, 371));
        working5_0 = new QPushButton(working5);
        working5_0->setObjectName(QStringLiteral("working5_0"));
        working5_0->setGeometry(QRect(0, 0, 75, 110));
        working5_0->setCursor(QCursor(Qt::PointingHandCursor));
        working5_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_0->setFlat(false);
        working5_1 = new QPushButton(working5);
        working5_1->setObjectName(QStringLiteral("working5_1"));
        working5_1->setGeometry(QRect(0, 15, 75, 110));
        working5_1->setCursor(QCursor(Qt::PointingHandCursor));
        working5_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_1->setFlat(false);
        working5_2 = new QPushButton(working5);
        working5_2->setObjectName(QStringLiteral("working5_2"));
        working5_2->setGeometry(QRect(0, 30, 75, 110));
        working5_2->setCursor(QCursor(Qt::PointingHandCursor));
        working5_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_2->setFlat(false);
        working5_3 = new QPushButton(working5);
        working5_3->setObjectName(QStringLiteral("working5_3"));
        working5_3->setGeometry(QRect(0, 45, 75, 110));
        working5_3->setCursor(QCursor(Qt::PointingHandCursor));
        working5_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_3->setFlat(false);
        working5_4 = new QPushButton(working5);
        working5_4->setObjectName(QStringLiteral("working5_4"));
        working5_4->setGeometry(QRect(0, 60, 75, 110));
        working5_4->setCursor(QCursor(Qt::PointingHandCursor));
        working5_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_4->setFlat(false);
        working5_5 = new QPushButton(working5);
        working5_5->setObjectName(QStringLiteral("working5_5"));
        working5_5->setGeometry(QRect(0, 75, 75, 110));
        working5_5->setCursor(QCursor(Qt::PointingHandCursor));
        working5_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_5->setFlat(false);
        working5_6 = new QPushButton(working5);
        working5_6->setObjectName(QStringLiteral("working5_6"));
        working5_6->setGeometry(QRect(0, 90, 75, 110));
        working5_6->setCursor(QCursor(Qt::PointingHandCursor));
        working5_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_6->setFlat(false);
        working5_7 = new QPushButton(working5);
        working5_7->setObjectName(QStringLiteral("working5_7"));
        working5_7->setGeometry(QRect(0, 105, 75, 110));
        working5_7->setCursor(QCursor(Qt::PointingHandCursor));
        working5_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_7->setFlat(false);
        working5_8 = new QPushButton(working5);
        working5_8->setObjectName(QStringLiteral("working5_8"));
        working5_8->setGeometry(QRect(0, 120, 75, 110));
        working5_8->setCursor(QCursor(Qt::PointingHandCursor));
        working5_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_8->setFlat(false);
        working5_9 = new QPushButton(working5);
        working5_9->setObjectName(QStringLiteral("working5_9"));
        working5_9->setGeometry(QRect(0, 135, 75, 110));
        working5_9->setCursor(QCursor(Qt::PointingHandCursor));
        working5_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_9->setFlat(false);
        working5_10 = new QPushButton(working5);
        working5_10->setObjectName(QStringLiteral("working5_10"));
        working5_10->setGeometry(QRect(0, 150, 75, 110));
        working5_10->setCursor(QCursor(Qt::PointingHandCursor));
        working5_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_10->setFlat(false);
        working5_11 = new QPushButton(working5);
        working5_11->setObjectName(QStringLiteral("working5_11"));
        working5_11->setGeometry(QRect(0, 165, 75, 110));
        working5_11->setCursor(QCursor(Qt::PointingHandCursor));
        working5_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_11->setFlat(false);
        working5_12 = new QPushButton(working5);
        working5_12->setObjectName(QStringLiteral("working5_12"));
        working5_12->setGeometry(QRect(0, 180, 75, 110));
        working5_12->setCursor(QCursor(Qt::PointingHandCursor));
        working5_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_12->setFlat(false);
        working5_13 = new QPushButton(working5);
        working5_13->setObjectName(QStringLiteral("working5_13"));
        working5_13->setGeometry(QRect(0, 195, 75, 110));
        working5_13->setCursor(QCursor(Qt::PointingHandCursor));
        working5_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_13->setFlat(false);
        working5_14 = new QPushButton(working5);
        working5_14->setObjectName(QStringLiteral("working5_14"));
        working5_14->setGeometry(QRect(0, 210, 75, 110));
        working5_14->setCursor(QCursor(Qt::PointingHandCursor));
        working5_14->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_14->setFlat(false);
        working5_15 = new QPushButton(working5);
        working5_15->setObjectName(QStringLiteral("working5_15"));
        working5_15->setGeometry(QRect(0, 225, 75, 110));
        working5_15->setCursor(QCursor(Qt::PointingHandCursor));
        working5_15->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_15->setFlat(false);
        working5_16 = new QPushButton(working5);
        working5_16->setObjectName(QStringLiteral("working5_16"));
        working5_16->setGeometry(QRect(0, 240, 75, 110));
        working5_16->setCursor(QCursor(Qt::PointingHandCursor));
        working5_16->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_16->setFlat(false);
        working5_17 = new QPushButton(working5);
        working5_17->setObjectName(QStringLiteral("working5_17"));
        working5_17->setGeometry(QRect(0, 255, 75, 110));
        working5_17->setCursor(QCursor(Qt::PointingHandCursor));
        working5_17->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working5_17->setFlat(false);
        working6 = new QWidget(working);
        working6->setObjectName(QStringLiteral("working6"));
        working6->setGeometry(QRect(540, 0, 75, 381));
        working6_0 = new QPushButton(working6);
        working6_0->setObjectName(QStringLiteral("working6_0"));
        working6_0->setGeometry(QRect(0, 0, 75, 110));
        working6_0->setCursor(QCursor(Qt::PointingHandCursor));
        working6_0->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_0->setFlat(false);
        working6_1 = new QPushButton(working6);
        working6_1->setObjectName(QStringLiteral("working6_1"));
        working6_1->setGeometry(QRect(0, 15, 75, 110));
        working6_1->setCursor(QCursor(Qt::PointingHandCursor));
        working6_1->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_1->setFlat(false);
        working6_2 = new QPushButton(working6);
        working6_2->setObjectName(QStringLiteral("working6_2"));
        working6_2->setGeometry(QRect(0, 30, 75, 110));
        working6_2->setCursor(QCursor(Qt::PointingHandCursor));
        working6_2->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_2->setFlat(false);
        working6_3 = new QPushButton(working6);
        working6_3->setObjectName(QStringLiteral("working6_3"));
        working6_3->setGeometry(QRect(0, 45, 75, 110));
        working6_3->setCursor(QCursor(Qt::PointingHandCursor));
        working6_3->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_3->setFlat(false);
        working6_4 = new QPushButton(working6);
        working6_4->setObjectName(QStringLiteral("working6_4"));
        working6_4->setGeometry(QRect(0, 60, 75, 110));
        working6_4->setCursor(QCursor(Qt::PointingHandCursor));
        working6_4->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_4->setFlat(false);
        working6_5 = new QPushButton(working6);
        working6_5->setObjectName(QStringLiteral("working6_5"));
        working6_5->setGeometry(QRect(0, 75, 75, 110));
        working6_5->setCursor(QCursor(Qt::PointingHandCursor));
        working6_5->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_5->setFlat(false);
        working6_6 = new QPushButton(working6);
        working6_6->setObjectName(QStringLiteral("working6_6"));
        working6_6->setGeometry(QRect(0, 90, 75, 110));
        working6_6->setCursor(QCursor(Qt::PointingHandCursor));
        working6_6->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_6->setFlat(false);
        working6_7 = new QPushButton(working6);
        working6_7->setObjectName(QStringLiteral("working6_7"));
        working6_7->setGeometry(QRect(0, 105, 75, 110));
        working6_7->setCursor(QCursor(Qt::PointingHandCursor));
        working6_7->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_7->setFlat(false);
        working6_8 = new QPushButton(working6);
        working6_8->setObjectName(QStringLiteral("working6_8"));
        working6_8->setGeometry(QRect(0, 120, 75, 110));
        working6_8->setCursor(QCursor(Qt::PointingHandCursor));
        working6_8->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_8->setFlat(false);
        working6_9 = new QPushButton(working6);
        working6_9->setObjectName(QStringLiteral("working6_9"));
        working6_9->setGeometry(QRect(0, 135, 75, 110));
        working6_9->setCursor(QCursor(Qt::PointingHandCursor));
        working6_9->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_9->setFlat(false);
        working6_10 = new QPushButton(working6);
        working6_10->setObjectName(QStringLiteral("working6_10"));
        working6_10->setGeometry(QRect(0, 150, 75, 110));
        working6_10->setCursor(QCursor(Qt::PointingHandCursor));
        working6_10->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_10->setFlat(false);
        working6_11 = new QPushButton(working6);
        working6_11->setObjectName(QStringLiteral("working6_11"));
        working6_11->setGeometry(QRect(0, 165, 75, 110));
        working6_11->setCursor(QCursor(Qt::PointingHandCursor));
        working6_11->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_11->setFlat(false);
        working6_12 = new QPushButton(working6);
        working6_12->setObjectName(QStringLiteral("working6_12"));
        working6_12->setGeometry(QRect(0, 180, 75, 110));
        working6_12->setCursor(QCursor(Qt::PointingHandCursor));
        working6_12->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_12->setFlat(false);
        working6_13 = new QPushButton(working6);
        working6_13->setObjectName(QStringLiteral("working6_13"));
        working6_13->setGeometry(QRect(0, 195, 75, 110));
        working6_13->setCursor(QCursor(Qt::PointingHandCursor));
        working6_13->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_13->setFlat(false);
        working6_14 = new QPushButton(working6);
        working6_14->setObjectName(QStringLiteral("working6_14"));
        working6_14->setGeometry(QRect(0, 210, 75, 110));
        working6_14->setCursor(QCursor(Qt::PointingHandCursor));
        working6_14->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_14->setFlat(false);
        working6_15 = new QPushButton(working6);
        working6_15->setObjectName(QStringLiteral("working6_15"));
        working6_15->setGeometry(QRect(0, 225, 75, 110));
        working6_15->setCursor(QCursor(Qt::PointingHandCursor));
        working6_15->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_15->setFlat(false);
        working6_16 = new QPushButton(working6);
        working6_16->setObjectName(QStringLiteral("working6_16"));
        working6_16->setGeometry(QRect(0, 240, 75, 110));
        working6_16->setCursor(QCursor(Qt::PointingHandCursor));
        working6_16->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_16->setFlat(false);
        working6_17 = new QPushButton(working6);
        working6_17->setObjectName(QStringLiteral("working6_17"));
        working6_17->setGeometry(QRect(0, 255, 75, 110));
        working6_17->setCursor(QCursor(Qt::PointingHandCursor));
        working6_17->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_17->setFlat(false);
        working6_18 = new QPushButton(working6);
        working6_18->setObjectName(QStringLiteral("working6_18"));
        working6_18->setGeometry(QRect(0, 270, 75, 110));
        working6_18->setCursor(QCursor(Qt::PointingHandCursor));
        working6_18->setStyleSheet(QStringLiteral("border-style: outset; border-width: 3px; border-color: yellow; border-radius: 5px"));
        working6_18->setFlat(false);
        menu = new QWidget(centralWidget);
        menu->setObjectName(QStringLiteral("menu"));
        menu->setGeometry(QRect(0, 0, 671, 31));
        save = new QPushButton(menu);
        save->setObjectName(QStringLiteral("save"));
        save->setGeometry(QRect(0, 0, 85, 28));
        load = new QPushButton(menu);
        load->setObjectName(QStringLiteral("load"));
        load->setGeometry(QRect(85, 0, 85, 28));
        undo = new QPushButton(menu);
        undo->setObjectName(QStringLiteral("undo"));
        undo->setGeometry(QRect(170, 0, 85, 28));
        hint = new QPushButton(menu);
        hint->setObjectName(QStringLiteral("hint"));
        hint->setGeometry(QRect(255, 0, 85, 28));
        info = new QWidget(centralWidget);
        info->setObjectName(QStringLiteral("info"));
        info->setGeometry(QRect(10, 560, 620, 20));
        moves = new QLabel(info);
        moves->setObjectName(QStringLiteral("moves"));
        moves->setGeometry(QRect(0, 0, 100, 20));
        moves->setStyleSheet(QStringLiteral(""));
        score = new QLabel(info);
        score->setObjectName(QStringLiteral("score"));
        score->setGeometry(QRect(100, 0, 100, 20));
        score->setStyleSheet(QStringLiteral(""));
        time = new QLabel(info);
        time->setObjectName(QStringLiteral("time"));
        time->setGeometry(QRect(200, 0, 100, 20));
        time->setStyleSheet(QStringLiteral(""));
        Solitaire->setCentralWidget(centralWidget);
        working->raise();
        stock_deck->raise();
        waste_deck->raise();
        target_deck_2->raise();
        target_deck_3->raise();
        target_deck_4->raise();
        target_deck_1->raise();
        menu->raise();
        info->raise();
        statusBar = new QStatusBar(Solitaire);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        Solitaire->setStatusBar(statusBar);

        retranslateUi(Solitaire);

        waste_deck->setDefault(false);
        target_deck_2->setDefault(false);
        target_deck_3->setDefault(false);
        target_deck_4->setDefault(false);
        target_deck_1->setDefault(false);


        QMetaObject::connectSlotsByName(Solitaire);
    } // setupUi

    void retranslateUi(QMainWindow *Solitaire)
    {
        Solitaire->setWindowTitle(QApplication::translate("Solitaire", "Solitaire", Q_NULLPTR));
        stock_deck->setText(QString());
        waste_deck->setText(QString());
        target_deck_2->setText(QString());
        target_deck_3->setText(QString());
        target_deck_4->setText(QString());
        target_deck_1->setText(QString());
        working0_12->setText(QString());
        working0_1->setText(QString());
        working0_5->setText(QString());
        working0_6->setText(QString());
        working0_8->setText(QString());
        working0_11->setText(QString());
        working0_3->setText(QString());
        working0_9->setText(QString());
        working0_7->setText(QString());
        working0_4->setText(QString());
        working0_10->setText(QString());
        working0_2->setText(QString());
        working0_0->setText(QString());
        working1_0->setText(QString());
        working1_1->setText(QString());
        working1_2->setText(QString());
        working1_3->setText(QString());
        working1_4->setText(QString());
        working1_5->setText(QString());
        working1_6->setText(QString());
        working1_7->setText(QString());
        working1_8->setText(QString());
        working1_9->setText(QString());
        working1_10->setText(QString());
        working1_11->setText(QString());
        working1_12->setText(QString());
        working1_13->setText(QString());
        working2_0->setText(QString());
        working2_1->setText(QString());
        working2_2->setText(QString());
        working2_3->setText(QString());
        working2_4->setText(QString());
        working2_5->setText(QString());
        working2_6->setText(QString());
        working2_7->setText(QString());
        working2_8->setText(QString());
        working2_9->setText(QString());
        working2_10->setText(QString());
        working2_11->setText(QString());
        working2_12->setText(QString());
        working2_13->setText(QString());
        working2_14->setText(QString());
        working3_0->setText(QString());
        working3_1->setText(QString());
        working3_2->setText(QString());
        working3_3->setText(QString());
        working3_4->setText(QString());
        working3_5->setText(QString());
        working3_6->setText(QString());
        working3_7->setText(QString());
        working3_8->setText(QString());
        working3_9->setText(QString());
        working3_10->setText(QString());
        working3_11->setText(QString());
        working3_12->setText(QString());
        working3_13->setText(QString());
        working3_14->setText(QString());
        working3_15->setText(QString());
        working4_0->setText(QString());
        working4_1->setText(QString());
        working4_2->setText(QString());
        working4_3->setText(QString());
        working4_4->setText(QString());
        working4_5->setText(QString());
        working4_6->setText(QString());
        working4_7->setText(QString());
        working4_8->setText(QString());
        working4_9->setText(QString());
        working4_10->setText(QString());
        working4_11->setText(QString());
        working4_12->setText(QString());
        working4_13->setText(QString());
        working4_14->setText(QString());
        working4_15->setText(QString());
        working4_16->setText(QString());
        working5_0->setText(QString());
        working5_1->setText(QString());
        working5_2->setText(QString());
        working5_3->setText(QString());
        working5_4->setText(QString());
        working5_5->setText(QString());
        working5_6->setText(QString());
        working5_7->setText(QString());
        working5_8->setText(QString());
        working5_9->setText(QString());
        working5_10->setText(QString());
        working5_11->setText(QString());
        working5_12->setText(QString());
        working5_13->setText(QString());
        working5_14->setText(QString());
        working5_15->setText(QString());
        working5_16->setText(QString());
        working5_17->setText(QString());
        working6_0->setText(QString());
        working6_1->setText(QString());
        working6_2->setText(QString());
        working6_3->setText(QString());
        working6_4->setText(QString());
        working6_5->setText(QString());
        working6_6->setText(QString());
        working6_7->setText(QString());
        working6_8->setText(QString());
        working6_9->setText(QString());
        working6_10->setText(QString());
        working6_11->setText(QString());
        working6_12->setText(QString());
        working6_13->setText(QString());
        working6_14->setText(QString());
        working6_15->setText(QString());
        working6_16->setText(QString());
        working6_17->setText(QString());
        working6_18->setText(QString());
        save->setText(QApplication::translate("Solitaire", "Save Game", Q_NULLPTR));
        load->setText(QApplication::translate("Solitaire", "Load Game", Q_NULLPTR));
        undo->setText(QApplication::translate("Solitaire", "Undo", Q_NULLPTR));
        hint->setText(QApplication::translate("Solitaire", "Hint", Q_NULLPTR));
        moves->setText(QString());
        score->setText(QString());
        time->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Solitaire: public Ui_Solitaire {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SOLITAIRE_H
